# Generated by Django 4.1.7 on 2023-04-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Portfolio', '0002_remove_personalinfo_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
