# Generated by Django 4.1.7 on 2023-04-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Portfolio', '0004_contact_alter_experience_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='language',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='project',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='soft_skill',
        ),
        migrations.RemoveField(
            model_name='personalinfo',
            name='tech_skill',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='cert',
            field=models.ImageField(null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(null=True, upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='soft_skills',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technical_skills',
            name='skill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
