# Generated by Django 4.1.7 on 2023-04-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Portfolio', '0005_remove_personalinfo_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soft_skills',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
