# Generated by Django 4.1.7 on 2023-04-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Portfolio', '0006_soft_skills_desc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Soft_Skills',
        ),
    ]
