# Generated by Django 4.1.7 on 2023-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Portfolio', '0007_delete_soft_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='education',
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
