# Generated by Django 4.1.7 on 2023-05-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Portfolio', '0009_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
